# Generated by Django 4.2.1 on 2023-06-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='quantity',
        ),
    ]
