# Generated by Django 4.2.1 on 2023-06-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_acceptance_options_and_more'),
        ('stock', '0002_remove_stockbatch_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_acceptance', to='products.acceptance', verbose_name='Партия')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='batches',
        ),
        migrations.DeleteModel(
            name='StockBatch',
        ),
        migrations.AddField(
            model_name='stockacceptance',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_acceptance', to='stock.stock', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='stock',
            name='acceptance',
            field=models.ManyToManyField(through='stock.StockAcceptance', to='products.acceptance', verbose_name='Приемка'),
        ),
    ]
