# Generated by Django 4.2.1 on 2023-06-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockacceptance_remove_stock_batches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockacceptance',
            old_name='batch',
            new_name='acceptance',
        ),
    ]
