# Generated by Django 4.2.1 on 2023-06-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_batch_stockacceptance_acceptance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='acceptance',
        ),
        migrations.DeleteModel(
            name='StockAcceptance',
        ),
    ]
