# Generated by Django 4.2.2 on 2023-06-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_acceptance_product_alter_acceptance_stock_and_more"),
        ("supplier", "0002_remove_supplier_email_supplier_contact_number_and_more"),
        ("stock", "0005_remove_stock_acceptance_delete_stockacceptance"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Категория продукта"
                    ),
                ),
                ("description", models.TextField(null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_set_product",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_set_stock",
                to="stock.stock",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_set_store",
                to="store.store",
                verbose_name="Магазин",
            ),
        ),
        migrations.CreateModel(
            name="Acceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_in",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена захода",
                    ),
                ),
                (
                    "price_out",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Цена продажи",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "entry_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время захода"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance",
                        to="stock.stock",
                        verbose_name="Склад",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приемка",
                "verbose_name_plural": "Приемки",
            },
        ),
    ]
