# Generated by Django 4.2.1 on 2023-05-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Имя поставщика"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Телефон номер"),
                ),
                ("email", models.EmailField(max_length=20, verbose_name="E-mail")),
                ("address", models.CharField(max_length=50, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
    ]
