# Generated by Django 4.2.1 on 2023-06-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_email_supplier_contact_number_and_more'),
        ('products', '0002_rename_batch_acceptance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptance',
            options={'verbose_name': 'Приемка', 'verbose_name_plural': 'Приемки'},
        ),
        migrations.RemoveField(
            model_name='acceptance',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='acceptance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='acceptance',
            name='price_in',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена захода'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='price_out',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
