# Generated by Django 4.2.1 on 2023-06-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stock_acceptance_delete_stockacceptance'),
        ('products', '0003_alter_acceptance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptance',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='stock.stock', verbose_name='Склад'),
        ),
    ]
