# Generated by Django 4.2.2 on 2023-06-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("supplier", "0002_remove_supplier_email_supplier_contact_number_and_more"),
        ("stock", "0005_remove_stock_acceptance_delete_stockacceptance"),
        ("products", "0004_acceptance_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptance",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acceptance_set_product",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="acceptance",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acceptance_set_stock",
                to="stock.stock",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="acceptance",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acceptance_set_supplier",
                to="supplier.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
